module.exports = {
  config: {
    name: "autoReply",
    version: "1.0.0",
    description: "Auto reply to common greetings in group",
    permission: 0,
    cooldowns: 5,
    category: "general",
  },

  start: async function({ api, event }) {
    const message = (event.body || "").toLowerCase();

    // সহজ রিপ্লাই ম্যাপ: মেসেজ -> রিপ্লাই
    const replies = {
      "kmn aco": "ভালোই আছি, তুমি কেমন?",
      "kemon aso": "আমি ভালই আছি, ধন্যবাদ!",
      "salam": "ওআলাইকুম সালাম, কেমন আছো?",
      "hi": "হাই, কিভাবে সাহায্য করতে পারি?",
      "hello": "হ্যালো! কেমন আছো?",
      "tumi ke": "আমি তোমার বট, যেকোনো প্রশ্ন করতে পারো।",
      "valo nai": "দুঃখিত শুনে, কিছু বলো আমাকে তোমাকে সাহায্য করতে পারি কি?",
      "thik achi": "দারুণ, তোমার দিন কেমন যাচ্ছে?",
      "dhonnobad": "তোমাকেও ধন্যবাদ!",
      "bye": "বিদায়! আবার কথা হবে।",
      "ki korcho": "আমি তো তোমার সেবায় আছি!",
      "kothay": "আমি তো ekhanei, তোমার সামনে।",
      "bhalo laglo": "খুশি হলাম শুনে!",
      "kemon lagche": "বেশ ভালো লাগছে, তুমি বলো কেমন লাগছে?",
      "shuvo ratri": "শুভ রাত্রি, মিষ্টি স্বপ্ন দেখো!",
      "shuvo sokal": "শুভ সকাল, তোমার দিন ভালো কাটুক!",
      "ki khobor": "সব ভালোই চলছে, তোমার কি খবর?",
      "khela hobe": "অবশ্যই! খেলা হবে!",
      "ashchi": "তোমার অপেক্ষায় আছি!",
      "koto baje": "দেখো তোমার ফোনে!",
      "thanda lagche": "নিজেকে গরম রাখো, খেয়াল রেখো!",
      "ghume jabo": "শুভরাত্রি, ভালো ঘুমাও!",
      "kichu bolo": "কি বলবো? তুমি বলো আগে!",
      "boka": "ভালো মানুষ হওয়া বোকামি না!",
      "mishti kotha": "তুমি আসলেই মিষ্টি!",
      "kotha bolo": "কথা বলবো, তুমি শোনাও!",
      "dorkar nai": "ঠিক আছে, তোমার ইচ্ছা!",
      "kamon aso": "ভালোই আছি, ধন্যবাদ!",
      "amar sathe kotha bolo": "অবশ্যই, কি জানতে চাও?",
      "ki khawa": "তোমার পছন্দ কি?",
      "kothay jachcho": "তুমি বলো আগে!",
      "kaj kemon": "সব ঠিকঠাক চলছে!",
      "bhalo lagche": "তুমি শুনে ভালো লাগলো!",
      "ki korbe": "তুমি বলো, আমি তো আছি!",
      "kothay aso": "তোমার পাশে, চিরদিন!",
      "kemon mone hocche": "ভালোই তো লাগে তোমার কথা শুনে!",
      "kothay dekha hobe": "যেখানে তুমি বলবে!",
      "tomar nam ki": "আমার নাম বট, তোমার কি?",
      "kothay ache": "তোমার কাছে, সদা প্রস্তুত!",
      "kamon achen": "ভাল আছি, আপনাদের জন্য!",
      "kamon aso": "ভালই আছি, তোমার কি খবর?",
      "kemon aso sobai": "সবাই ভালো আছে, তোমারাও ভালো থাকবে!",
      "bujhte parchi na": "দয়া করে আবার বলো, বুঝতে সাহায্য করব!",
      "ki hoyeche": "সব কিছু ঠিকঠাক আছে, তুমি বলো কি খবর?",
      "khub bhalo": "খুশি হলাম শুনে!",
      "bhalo nai": "দুঃখিত শুনে, কিছু বলো তোমাকে সাহায্য করবো!",
      "bhalo laglo tomar kotha": "আমার জন্য বড় কথা, ধন্যবাদ!",
      "dure jao": "না না, আমি তোমার পাশে থাকবো!",
      "ami ekhane": "তুমি আছো, এটাই অনেক!",
      "kothay kemon": "সব ভালো, তোমার কি খবর?",
      "ki korlam": "তুমি তো সেরা করছো!",
      "kichu bolte chai": "আমি শুনছি, বলো!",
      "tomake bhalobashi": "আমিও তোমাকে!",
      "dhonnobad tomar jonno": "আমার পক্ষ থেকে ধন্যবাদ তোমাকেও!",
      "tomar ki khobor": "সব ভালোই চলছে, ধন্যবাদ!",
      "kothay jaccho": "আমি তো কোথাও যাচ্ছি না, এখানে আছি!",
      "kemon achho": "ভালো আছি, তুমি কেমন?",
      "kothay chilam": "আমি এখানে তোমার জন্য অপেক্ষা করছিলাম!",
      "ki korcho ekhane": "তোমার সেবায় আছি!",
      "shuvo din": "শুভ দিন তোমার জন্য!",
      "kemon achen sobai": "সবাই ভালো আছে, তোমারাও ভালো থাকবে!",
      "kemon lage": "ভালই লাগে তোমার কথা শুনে!",
      "ami bhalo": "খুশি হলাম শুনে!",
      "kemon laglo tomar sathe kotha": "আমার ভালো লাগলো, তুমি বলো!",
      "kichu kotha": "বলতে থাকো, আমি শুনছি!",
      "tomar sathe kotha bolte bhalo laglo": "আমারও খুব ভালো লাগলো!",
      "tomar dorkar ki": "তুমি যা চাও বলো, আমি আছি!",
      "bhalo thako": "তুমি ও ভালো থাকো!",
      "tomake dekhte bhalo laglo": "আমারও তোমাকে দেখতে ভালো লাগলো!",
      "kichu proshno ache": "বলো, আমি সাহায্য করবো!",
      "bhalo laglo tomar shathe kotha bole": "খুশি হলাম শুনে!",
      "ki korbe aj": "আজকের জন্য তোমার পরিকল্পনা কী?",
      "kothay jabo": "যেখানে তুমি বলবে, আমি তোমার পাশে আছি!",
      "ki khabar": "সব ভালোই চলছে, তুমি বলো!",
      "kemon chole": "সব ঠিকঠাক চলছে!",
      "tomar asha ki": "তুমি যা চাও, আমি সাহায্য করতে প্রস্তুত!",
      "kemon asey sobar": "সবাই ভালো আছে, তোমারাও ভালো থাকো!",
      "tomar mon kemon": "ভালো আছে, তুমি বলো কেমন?",
      "kothay asa": "তোমার কাছে, চিরকাল!",
      "kothay jete chai": "যেখানে তোমার ইচ্ছে!",
      "ki shikhso": "প্রতিদিন নতুন কিছু শিখি!",
      "kemon lagche amar kotha": "ভালই লাগছে, তুমি বলো!",
      "kibhabe aso": "ভালোই আসছি, ধন্যবাদ!",
      "kotha bolo amake": "বলছি তো, তুমি বলো!",
      "tomake miss kori": "আমি ও তোমাকে মিস করছি!",
      "kibhabe help korte pari": "তুমি কি জানতে চাও?",
      "tomar kotha mone porche": "আমারও তোমার কথা মনে পড়ছে!",
      "ki shoja kore bolo": "শুধু বলো, আমি শুনছি!",
      "amar dorkar ache": "বলো কি দরকার, আমি আছি!",
      "tomake dhonnobad": "আমার পক্ষ থেকে ধন্যবাদ তোমাকেও!",
      "kothay giyechho": "আমি তো এখানে আছি, তোমার পাশে!",
      "kothay jabe aj": "যেখানে ইচ্ছে তোমার!",
      "ki obostha": "ভালই আছি, তোমার কি অবস্থা?",
      "tomar sathe kotha bole valo laglo": "আমারও খুব ভালো লাগলো!",
      "bhalo thako sada": "তুমি ও ভালো থাকো সদা!",
      "kibhabe aso tumi": "ভালই আসছি, ধন্যবাদ!",
      "tomake kibhabe pabo": "আমি তো তোমার পাশে আছি!",
      "kothay thako": "তোমার কাছে, চিরকাল!",
      "ki jante chao": "যা কিছু জানতে চাও বলো!",
      "kemon chinta koro": "ভালই ভাবছি, তুমি বলো!",
      "tomar jonno dua kori": "ধন্যবাদ, তোমার জন্য আমারও দোয়া থাকবে!",
      "kothay jai": "যেখানে তুমি বলো, আমি তোমার সাথে!",
      "tomake ami bhalobasi": "আমিও তোমাকে!",
      "ki kotha bolo": "বলছি তো, তুমি বলো!",
      "kothay dakte chai": "যেখানে তুমি বলবে, আমি সেখানে থাকব!",
      "tomake chinta kori": "আমি তোমার জন্য চিন্তা করি!",
      "kemon aso tumi sobar": "ভালই আছি, সবাই ভালো থাকবে!",
      "ki khobor tomar sathe": "সব ভালোই চলছে, তুমি বলো!",
      "bhalo achi ami": "ভালো শুনে ভালো লাগলো!",
      "kothay esecho": "আমি তো এখানে, তোমার পাশে!",
      "ki kori ekhane": "তুমি যা চাও করো, আমি তোমার পাশে!",
      "ki khobor sobai": "সবাই ভালো আছে, তোমারাও ভালো থাকবে!",
    };

    for (const key in replies) {
      if (message.includes(key)) {
        return api.sendMessage(replies[key], event.threadID, event.messageID);
      }
    }
  }
};
